type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "CTO List (Inaugural Member) ğŸ†"
subtitle = "UbiQuant â€” Company-wide High-Potential Technical Leadership Program"
date = "2024"
content = ""

[[items]]
title = "Distinguished Paper Award ğŸ†"
subtitle = "Proceedings of the 28th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS'23)"
date = "2023"
content = ""

