

[[news]]
date = "2023-06"
content = "I have successfully obtained my Ph.D. degree ğŸ“"

[[news]]
date = "2023-03"
content = "Our paper titled 'A Generic Service to Provide In-Network Aggregation for Key-Value Streams' received the Distinguished Paper Award at ASPLOS 2023 ğŸ†"