[[news]]
date = "2024-12"
content = "I joined ScitiX AI as a founding member. ğŸš€"

[[news]]
date = "2024-06"
content = "I founded and lead the AI Infrastructure R&D group at UbiQuant. âš™ï¸"

[[news]]
date = "2024-03"
content = "Selected as the first member of UbiQuantâ€™s CTO List, a high-potential technical leadership program. ğŸ†"

[[news]]
date = "2023-07"
content = "I started my position at UbiQuant under the Wutong Program (æ¢§æ¡è®¡åˆ’), a premier Technical Talent Program. ğŸš€"

[[news]]
date = "2023-06"
content = "I earned my Ph.D. in Computer Science ğŸ“"

[[news]]
date = "2023-03"
content = "Our paper titled 'A Generic Service to Provide In-Network Aggregation for Key-Value Streams' received the Distinguished Paper Award at ASPLOS 2023. ğŸ†"