type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Distinguished Paper Award"
subtitle = "Proceedings of the 28th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS'23)"
date = "2023"
content = ""

